# server:
#     port: 8080


# spring:
#     datasource:
#         url: jdbc:mysql://localhost:3306/demo
#         driverClassName: com.mysql.cj.jdbc.Driver
#         username: root
#         password: root

# jpa:
#     show-sql: true
#     hibernate:
#         ddl-auto: update

